INSERT INTO Products (ProductName, ProductPrice, CategoryID, ProductImageURL, ProductDescription) VALUES
('sky blue', 10, 1, 'nail-photos/3.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('grey blue', 10, 1, 'nail-photos/4.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('sage green', 10, 1, 'nail-photos/5.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('lavendar', 10, 1, 'nail-photos/6.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('grey', 10, 1, 'nail-photos/7.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('top coat', 10, 1, 'nail-photos/8.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('black', 10, 1, 'nail-photos/9.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('cream', 10, 1, 'nail-photos/10.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('baby pink', 10, 1, 'nail-photos/11.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('indigo blue', 10, 1, 'nail-photos/12.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('top and base coat', 10, 1, 'nail-photos/13.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('blood red', 10, 1, 'nail-photos/14.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('peach', 10, 1, 'nail-photos/15.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('baby clipper', 5, 4, 'nail-photos/babyclippers.jpeg', 'This baby clippers are essential for taking care of your baby. It is designed for the softness of baby nails.'),
('blue fire press ons', 20, 2, 'nail-photos/bluefirepressons.jpeg', 'Perfect blue fire nail design. Its already made for you. Just press it on with the provided glue and your ready to go.'),
('buffer', 5, 4, 'nail-photos/buffers.jpeg', 'Nail buffer for the perfect nail beds.'),
('cavier beads', 30, 3, 'nail-photos/caviorbeadsset.jpeg', 'Cavier beads that have different colors for nail designs'),
('checkered press ons', 20, 2, 'nail-photos/checkeredpressons.jpeg', 'Perfect checkered nail design. Its already made for you. Just press it on with the provided glue and your ready to go.'),
('cheetah press ons', 20, 2, 'nail-photos/cheetahpressons.webp', 'Perfect cheetah nail design. Its already made for you. Just press it on with the provided glue and your ready to go.'),
('colorful press ons', 20, 2, 'nail-photos/colorfulpressons.webp', 'Perfect colorful pastel nail design. Its already made for you. Just press it on with the provided glue and your ready to go.'),
('flowers', 30, 3, 'nail-photos/flowers.jpeg', 'Flower accesories in different shapes and sizes.'),
('gold flakes', 30, 3, 'nail-photos/goldflakes.webp', 'Gold flakes that are easy to use.'),
('silver flakes', 30, 3, 'nail-photos/silverflakes.webp', 'Silver flakes that are easy to use.'),
('baby blue', 10, 1, 'nail-photos/images2.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('silver', 10, 1, 'nail-photos/images.jpeg', 'This product helps in growing out nails. It is advised to layer two times for maximum coverage.'),
('nail clippers', 5, 4, 'nail-photos/nailclippers.jpeg', 'Nail clippers for hands'),
('nail files', 5, 4, 'nail-photos/nailfiles.jpeg', 'Nail files, comes in a pack of 3'),
('nail polish remover', 30, 4, 'nail-photos/nailpolishremover.jpeg', 'Nail polish remover that has 80% aceton.'),
('pink glitter', 10, 3, 'nail-photos/pinkglitter.webp', 'Pink glitters for that pop of color'),
('pink nails glitter press ons', 50, 2, 'nail-photos/pinknailsglitterpressons.webp', 'Perfect pink nail design. Its already made for you. Just press it on with the provided glue and your ready to go.'),
('snowflake design press ons', 50, 2, 'nail-photos/snowflakedesignpressons.webp', 'Perfect snowflake design. Its already made for you. Just press it on with the provided glue and your ready to go.'),
('star moon nail rhinestones', 30, 3, 'nail-photos/starmoonnailrhinestones.webp', 'Perfect rhinestones for a fairytale experience.'),
('toe nail clippers', 30, 4, 'nail-photos/toenails.jpeg', 'Nail clippers for your foot.');